plugins:
  - "@dotcom-tool-kit/component"
  - "@dotcom-tool-kit/jest"
  - "@dotcom-tool-kit/eslint"
  - "@dotcom-tool-kit/mocha"
  - "@dotcom-tool-kit/prettier"
  - "@dotcom-tool-kit/lint-staged"
  - "@dotcom-tool-kit/upload-assets-to-s3"
hooks:
  git:precommit:
    - SecretSquirrel
    - LintStaged
  test:local:
    - Eslint
    - Mocha
    - JestLocal
  test:ci:
    - Eslint
    - Mocha
    - JestCI
options:
  "@dotcom-tool-kit/jest": {}
  "@dotcom-tool-kit/mocha": {}
  "@dotcom-tool-kit/eslint": {}
  "@dotcom-tool-kit/upload-assets-to-s3": {}
  "@dotcom-tool-kit/circleci":
    nodeVersion: 18.19-browsers
