name: Deploy
on:
  push:
    branches:
      - main
defaults:
  run:
    shell: bash
jobs:
  gh-pages-deploy:
    name: Deploying Storybook
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 14.x
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
      - run: git config --global url."https://${{ secrets.NEXT_USER_PAT }}@github.com/".insteadOf ssh://git@github.com/
      - run: npm install -g npm@7.24.2
      - run: make install
      - run: npm run build-storybook
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
