name: Deploy
on:
  push:
    branches:
      - rb-remove-hbs-new
defaults:
  run:
    shell: bash
jobs:
  gh-pages-deploy:
    name: Deploying Storybook
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1
        with:
          version: 12.x
      - uses: actions/checkout@v2
      - run: make install
      - run: npm run build-storybook
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
